a= int(input("enter 1 Number:"))
b= int(input("enter 2 Number:"))
print(a)
print("enter addition of a&b number-")
print(a+b)
print("enter  substraction  of a&b number-")
print(a-b)
print(b)
print("enter Multipication  a&b number-")
print(a*b)
print("enter Division  a&b number-")
print(a/b)